<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{titulo}</title>
    <link rel="stylesheet" href="../css/style.min.css">
</head>
<body>
    <div class="container">
        <div class="topo">
            <h1>MusicBox</h1>
            <a class="home" href="../../index.html"><img src="../../assets/images/home.png" alt=""></a>
        </div>

        <div class="slide">
            <div class="slideshow" id="slideshow">
                <div class="slideshow_area">
                    <div class="slides">
                            <p class="textos">{titulo}</p>
                    </div>
    
                     <div class="slides">
                            <p class="textos">{musica}</p>
                    </div>   
                        
                    <div class="slides">
                            <p class="textos">{estilo}</p>
                    </div>
                </div>
            </div>
        </div>
    

        <div class="slide_img">
            <div class="slideshow_img" id="slideshow_img">
                <div class="slideshow_img_area">
                    <div class="slides_img" style="background-image: url('../../assets/images/artist/{artist}/bg1.jpg');">
                        <div class="textos_img"><p>{texto1}</p></div>
                    </div>

                    <div class="slides_img" style="background-image: url('../../assets/images/artist/{artist}/bg2.jpg');">
                        <div class="textos_img"><p>{texto2}</p></div>
                    </div>
                    <div class="slides_img" style="background-image: url('../../assets/images/artist/{artist}/bg3.jpg');">
                        <div class="textos_img"><p>{texto3}</p></div>
                    </div>
                    <div class="slides_img" style="background-image: url('../../assets/images/artist/{artist}/bg4.jpg');">
                        <div class="textos_img"><p>{texto4}</p></div>
                    </div>
                    <div class="slides_img" style="background-image: url('../../assets/images/artist/{artist}/bg5.jpg');">
                        <div class="textos_img"><p>{texto5}</p></div>
                    </div>
                    <div class="slides_img" style="background-image: url('../../assets/images/artist/{artist}/bg6.jpg');">
                        <div class="textos_img"><p>{texto6}</p></div>
                    </div>
                    <div class="slides_img" style="background-image: url('../../assets/images/artist/{artist}/bg7.jpg');">
                        <div class="textos_img"><p>{texto7}</p></div>
                    </div>
                </div>
            </div>

            <div class="audio">
                    <audio controls="" autoplay preload="auto" loop src="../../assets/musics/{music}"></audio>
                </div>
        </div>

        

        <div class="footer">
            <p>Para maiores informações visite: <a href="{link}" target="blank">{titulo} - Wikipédia</a></p>
            <div class="by">
                <p>By: AlmeidaFabiO</p>
            </div>
        </div>
    </div>

    <script src="../js/slides.min.js"></script>
</body>
</html>